FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY fclones-bin /usr/local/bin/fclones
RUN chmod +x /usr/local/bin/fclones
ENTRYPOINT ["/usr/local/bin/fclones"]
CMD ["--help"]
